export function el(id){ return document.getElementById(id); }
export function safeAddListener(id,event,handler){ const element=el(id); if(element) element.addEventListener(event,handler); }
export function escapeHtml(v){ return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;'); }
export function toast(msg,isError=false){ const t=el('toast'); if(!t){ console.log(msg); return; } t.textContent=msg; t.style.display='block'; if(isError){t.style.border='1px solid #fecaca';t.style.background='#fef2f2';t.style.color='#991b1b';} else {t.style.border='1px solid var(--border)';t.style.background='#fff';t.style.color='#0f172a';} clearTimeout(window.__toastTimer); window.__toastTimer=setTimeout(()=>{t.style.display='none';},3200); console.log(msg); }
export function toNumber(value){ const n=parseFloat(value); return Number.isFinite(n)?n:0; }
export function roundNumber(value,decimals){ const factor=Math.pow(10,decimals); return Math.round((value+Number.EPSILON)*factor)/factor; }
export function formatDateTime(value){ if(!value)return '—'; const raw=String(value); if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const [y,m,d]=raw.split('-').map(Number); return new Date(y,m-1,d).toLocaleDateString('en-AU',{day:'2-digit',month:'short'});} const d=new Date(value); const isMidnightUtc=d.getUTCHours()===0&&d.getUTCMinutes()===0&&d.getUTCSeconds()===0; if(isMidnightUtc) return d.toLocaleDateString('en-AU',{day:'2-digit',month:'short',timeZone:'UTC'}); return d.toLocaleString('en-AU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}); }
export function combineDateTime(dateValue,timeValue){ if(!dateValue)return null; if(!timeValue)return dateValue; return new Date(`${dateValue}T${timeValue}`).toISOString(); }
export function toInputDate(value){ if(!value)return ''; const raw=String(value); if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw; const d=new Date(value); if(Number.isNaN(d.getTime()))return ''; const isMidnightUtc=d.getUTCHours()===0&&d.getUTCMinutes()===0&&d.getUTCSeconds()===0; if(isMidnightUtc)return raw.slice(0,10); return d.toISOString().slice(0,10); }
