import { sb } from '../core/supabaseClient.js';
import { state } from '../core/state.js';
import { el, toast } from '../core/utils.js';

export async function loadPostcodes(){ if(state.auPostcodes?.length)return state.auPostcodes; let allRows=[], from=0, pageSize=1000, keepGoing=true; while(keepGoing){ const {data,error}=await sb.from('au_postcodes').select('suburb,state,postcode').range(from,from+pageSize-1); if(error){console.error('Error loading postcodes:',error); return [];} const rows=data||[]; allRows=allRows.concat(rows); if(rows.length<pageSize)keepGoing=false; else from+=pageSize; } state.auPostcodes=allRows; console.log('Postcodes loaded once:',state.auPostcodes.length); return state.auPostcodes; }
export function initInlineSuburbSearch(inputId,prefix){ const input=el(inputId); if(!input)return; let results=input.parentNode.querySelector('.suburb-dropdown'); if(!results){results=document.createElement('div'); results.className='suburb-dropdown'; input.parentNode.style.position='relative'; input.parentNode.appendChild(results);} input.addEventListener('input',async()=>{const val=input.value.toLowerCase().trim(); results.innerHTML=''; results.style.display='none'; if(!val)return; if(!state.auPostcodes?.length)await loadPostcodes(); const matches=state.auPostcodes.filter(p=>(p.suburb||'').toLowerCase().includes(val)).slice(0,10); if(!matches.length)return; results.style.display='block'; matches.forEach(p=>{const div=document.createElement('div'); div.textContent=`${p.suburb} ${p.state} ${p.postcode}`; div.onclick=()=>{input.value=p.suburb; el(`${prefix}State`).value=p.state||''; el(`${prefix}Postcode`).value=p.postcode||''; results.style.display='none';}; results.appendChild(div);});}); document.addEventListener('click',e=>{if(!results.contains(e.target)&&e.target!==input) results.style.display='none';}); }
export async function loadAllAddresses(){ let query=sb.from('addresses').select('*'); const role=state.currentProfile?.role||null; if(role==='customer'&&state.currentCustomerId)query=query.eq('customer_id',state.currentCustomerId); const {data,error}=await query; if(error){console.error('Error loading addresses:',error); return;} state.allAddresses=data||[]; }
export function renderAddressDropdown(selectId,type){ const sel=el(selectId); if(!sel)return; const filtered=state.allAddresses.filter(a=>a.address_type===type||a.address_type==='both'); sel.innerHTML='<option value="">Select address</option>'; filtered.forEach(a=>{ const opt=document.createElement('option'); opt.value=a.id; opt.textContent=`${a.company_name||''} - ${a.suburb||''}`; sel.appendChild(opt); }); }
export function initAddressDropdowns(){ renderAddressDropdown('pickupAddressSelect','pickup'); renderAddressDropdown('deliveryAddressSelect','delivery'); }
export function onAddressChange(selectId,prefix){ const selectEl=el(selectId); if(!selectEl)return; const addr=state.allAddresses.find(a=>a.id==selectEl.value); const refs={company:el(`${prefix}Company`),contact:el(`${prefix}-contact`),phone:el(`${prefix}-phone`),line:el(`${prefix}AddressLine`),suburb:el(`${prefix}Suburb`),state:el(`${prefix}State`),postcode:el(`${prefix}Postcode`)}; if(!addr){Object.values(refs).forEach(x=>{if(x)x.value='';}); [refs.state,refs.postcode].forEach(f=>{if(f)f.style.background='';}); return;} refs.company.value=addr.company_name||''; refs.contact.value=addr.contact_name||''; refs.phone.value=addr.contact_phone||''; refs.line.value=addr.address_line||''; refs.suburb.value=addr.suburb||''; refs.state.value=addr.state||''; refs.postcode.value=addr.postcode||''; [refs.state,refs.postcode].forEach(f=>{if(f)f.style.background='#f1f5f9';}); }
export function openAddressModal(defaultType='both'){ el('addr-type').value=defaultType; ['addr-company','addr-contact','addr-phone','addr-line','addr-suburb','addr-state','addr-postcode'].forEach(id=>{if(el(id))el(id).value='';}); state.suburbSelected=false; el('address-modal')?.classList.remove('hidden'); initSuburbAutocomplete(); setTimeout(()=>el('addr-company')?.focus(),50); }
export function closeAddressModal(){ el('address-modal')?.classList.add('hidden'); }
export function initSuburbAutocomplete(){ const input=el('addr-suburb'); const results=el('suburb-results'); if(!input||!results)return; input.oninput=()=>{ state.suburbSelected=false; const val=input.value.toLowerCase().trim(); results.innerHTML=''; results.style.display='none'; if(!val)return; const matches=(state.auPostcodes||[]).filter(p=>(p.suburb||'').toLowerCase().includes(val)).slice(0,10); if(!matches.length)return; results.style.display='block'; matches.forEach(p=>{ const div=document.createElement('div'); div.textContent=`${p.suburb} ${p.state} ${p.postcode}`; div.onclick=()=>{ input.value=p.suburb; el('addr-state').value=p.state||''; el('addr-postcode').value=p.postcode||''; state.suburbSelected=true; results.style.display='none'; }; results.appendChild(div); }); }; document.addEventListener('click',e=>{if(!results.contains(e.target)&&e.target!==input)results.style.display='none';}); }
export async function saveAddress(){ const company=el('addr-company').value.trim(), addressLine=el('addr-line').value.trim(), suburb=el('addr-suburb').value.trim(), stateVal=el('addr-state').value.trim(), postcode=el('addr-postcode').value.trim(); if(!company)return toast('Company is required',true); if(!addressLine)return toast('Street address is required',true); if(!suburb)return toast('Suburb is required',true); if(!state.suburbSelected)return toast('Please select a suburb from the list',true); if(!stateVal)return toast('State must be selected from suburb',true); if(!postcode)return toast('Postcode must be selected from suburb',true); const newAddress={company_name:company,contact_name:el('addr-contact').value,contact_phone:el('addr-phone').value,address_line:addressLine,suburb,state:stateVal,postcode,address_type:el('addr-type').value,customer_id:state.currentProfile?.role==='customer'?state.currentCustomerId:null,created_by_user_id:state.currentProfile?.id}; const {error}=await sb.from('addresses').insert([newAddress]); if(error){toast('Error saving address',true); console.error(error); return;} toast('Address saved'); await loadAllAddresses(); initAddressDropdowns(); closeAddressModal(); }
export function bindAddressEvents(){ el('pickupAddressSelect')?.addEventListener('change',()=>onAddressChange('pickupAddressSelect','pickup')); el('deliveryAddressSelect')?.addEventListener('change',()=>onAddressChange('deliveryAddressSelect','delivery')); el('saveAddressBtn')?.addEventListener('click',saveAddress); el('cancelAddressBtn')?.addEventListener('click',closeAddressModal); window.openAddressModal=openAddressModal; window.closeAddressModal=closeAddressModal; window.saveAddress=saveAddress; window.onAddressChange=onAddressChange; }
