import { state } from '../core/state.js';
import { el, escapeHtml, toNumber, roundNumber, toast } from '../core/utils.js';

export function calculateItemCubic(item){ return roundNumber(toNumber(item.qty)*toNumber(item.length_m)*toNumber(item.width_m)*toNumber(item.height_m),3); }
export function calculateBookingTotals(){ let totalWeight=0,totalCubic=0; state.bookingItems.forEach(item=>{ totalWeight+=toNumber(item.qty)*toNumber(item.weight_kg); totalCubic+=calculateItemCubic(item); }); return {totalWeight:roundNumber(totalWeight,2),totalCubic:roundNumber(totalCubic,3)}; }
export function updateBookingTotalsUI(){ const totals=calculateBookingTotals(); if(el('bookingTotalWeight'))el('bookingTotalWeight').textContent=totals.totalWeight.toFixed(2).replace('.00','')+' kg'; if(el('bookingTotalCubic'))el('bookingTotalCubic').textContent=totals.totalCubic.toFixed(3)+' m³'; }
export function addBookingItem(defaults={}){ state.bookingItemCounter+=1; state.bookingItems.push({local_id:state.bookingItemCounter,description:defaults.description||'',item_type:defaults.item_type||'',qty:defaults.qty||'',length_m:defaults.length_m||'',width_m:defaults.width_m||'',height_m:defaults.height_m||'',weight_kg:defaults.weight_kg||''}); renderBookingItems(); }
export function removeBookingItem(localId){ state.bookingItems=state.bookingItems.filter(item=>String(item.local_id)!==String(localId)); if(!state.bookingItems.length){addBookingItem();return;} renderBookingItems(); }
export function updateBookingItem(localId,field,value){ const item=state.bookingItems.find(r=>String(r.local_id)===String(localId)); if(!item)return; item[field]=value; updateRowCubic(localId); updateBookingTotalsUI(); }
function updateRowCubic(localId){ const row=document.querySelector(`tr[data-local-id="${localId}"]`); if(!row)return; const item=state.bookingItems.find(i=>String(i.local_id)===String(localId)); if(!item)return; const cubicCell=row.querySelector('.cubic-display'); if(cubicCell)cubicCell.textContent=calculateItemCubic(item).toFixed(3); }
export function getBookingItemsForSave(){ return state.bookingItems.map(item=>({description:String(item.description||'').trim(),item_type:String(item.item_type||'').trim(),qty:toNumber(item.qty)||1,length_m:item.length_m===''?null:toNumber(item.length_m),width_m:item.width_m===''?null:toNumber(item.width_m),height_m:item.height_m===''?null:toNumber(item.height_m),weight_kg:item.weight_kg===''?null:toNumber(item.weight_kg),cubic_m3:calculateItemCubic(item)})).filter(item=>item.description||item.item_type||item.length_m||item.width_m||item.height_m||item.weight_kg); }
export function validateBookingItems(items){ if(!items.length){toast('Add at least one freight item',true);return false;} for(const item of items){ if(!item.description){toast('Each freight item needs a description',true);return false;} if(!item.item_type){toast('Each freight item needs a type',true);return false;} if(!item.qty||item.qty<=0){toast('Each freight item needs a quantity greater than 0',true);return false;} if(!item.length_m||!item.width_m||!item.height_m){toast('Each freight item needs length, width and height in metres',true);return false;} } return true; }
export function renderBookingItems(){ const body=el('bookingItemsBody'); if(!body)return; if(!state.bookingItems.length){state.bookingItemCounter+=1; state.bookingItems=[{local_id:state.bookingItemCounter,description:'',item_type:'',qty:'',length_m:'',width_m:'',height_m:'',weight_kg:''}];} body.innerHTML=state.bookingItems.map(item=>{ const cubic=calculateItemCubic(item); return `<tr data-local-id="${escapeHtml(item.local_id)}"><td><input value="${escapeHtml(item.description)}" placeholder="e.g. Pallets" data-item-id="${escapeHtml(item.local_id)}" data-field="description" class="booking-item-input" /></td><td><select data-item-id="${escapeHtml(item.local_id)}" data-field="item_type" class="booking-item-input"><option value="" ${!item.item_type?'selected':''}>Select...</option>${['Full Load','Pallet','Skid','Carton','Crate','Loose','Other'].map(t=>`<option value="${t}" ${item.item_type===t?'selected':''}>${t}</option>`).join('')}</select></td><td><input type="number" min="0" step="1" value="${escapeHtml(item.qty)}" data-item-id="${escapeHtml(item.local_id)}" data-field="qty" class="booking-item-input" /></td><td><input type="number" min="0" step="0.001" value="${escapeHtml(item.length_m)}" data-item-id="${escapeHtml(item.local_id)}" data-field="length_m" class="booking-item-input" /></td><td><input type="number" min="0" step="0.001" value="${escapeHtml(item.width_m)}" data-item-id="${escapeHtml(item.local_id)}" data-field="width_m" class="booking-item-input" /></td><td><input type="number" min="0" step="0.001" value="${escapeHtml(item.height_m)}" data-item-id="${escapeHtml(item.local_id)}" data-field="height_m" class="booking-item-input" /></td><td><input type="number" min="0" step="0.01" value="${escapeHtml(item.weight_kg)}" data-item-id="${escapeHtml(item.local_id)}" data-field="weight_kg" class="booking-item-input" /></td><td><span class="cubic-display">${cubic.toFixed(3)}</span></td><td><button type="button" class="remove-item-btn" data-remove-item-id="${escapeHtml(item.local_id)}">×</button></td></tr>`}).join(''); updateBookingTotalsUI(); }
export function resetBookingItems(){ state.bookingItems=[]; state.bookingItemCounter=0; addBookingItem(); }
export function bindFreightEvents(){ document.addEventListener('input',evt=>{const input=evt.target.closest('.booking-item-input'); if(!input)return; updateBookingItem(input.getAttribute('data-item-id'),input.getAttribute('data-field'),input.value);}); document.addEventListener('change',evt=>{const input=evt.target.closest('.booking-item-input'); if(!input)return; updateBookingItem(input.getAttribute('data-item-id'),input.getAttribute('data-field'),input.value);}); document.addEventListener('click',evt=>{const btn=evt.target.closest('[data-remove-item-id]'); if(!btn)return; removeBookingItem(btn.getAttribute('data-remove-item-id'));}); }
